# Generated by Django 4.0.5 on 2022-07-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_worklog_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
