# Generated by Django 4.0.5 on 2022-07-16 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_worklog_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('in_date', models.DateTimeField(blank=True, null=True)),
                ('in_time', models.TimeField(blank=True, null=True)),
                ('out_date', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.TimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
